CREATE DATABASE QLSANBONG
GO

USE QLSANBONG
GO

CREATE TABLE ACCOUNT
(
	UserName VARCHAR(100) NOT NULL,
	Password VARCHAR(15) NOT NULL,
	DisplayName NVARCHAR(100) NOT NULL,
	Role INT DEFAULT 0,
	CONSTRAINT PK_ACCOUNT PRIMARY KEY (UserName)
)

CREATE TABLE LOAISAN
(
	MaLoai INT IDENTITY(1,1) NOT NULL,
	TenLoai NVARCHAR(100) NOT NULL,
	GiaThue FLOAT DEFAULT 100000,
	CONSTRAINT PK_LOAISAN PRIMARY KEY (MaLoai)
)

CREATE TABLE SANBONG 
(
	MaSan INT IDENTITY(1,1) NOT NULL,
	TenSan NVARCHAR(100) NOT NULL,
	MaLoai INT NOT NULL,
	CONSTRAINT PK_SANBONG PRIMARY KEY (MaSan),
	CONSTRAINT FK_SANBONG_LOAISAN FOREIGN KEY (MaLoai) REFERENCES LOAISAN(MaLoai)
)

CREATE TABLE KHACHHANG
(
	MaKH INT IDENTITY(1,1) NOT NULL,
	TenKH NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) DEFAULT N'Chưa xác định',
	SDT VARCHAR(10) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MaKH)
)

CREATE TABLE LICHDATSAN
(
	MaLich INT IDENTITY(1,1) NOT NULL,
	ThoiGianBD DATETIME DEFAULT GETDATE(),
	ThoiGianKT DATETIME NOT NULL,
	MaKH INT NOT NULL,
	MaSan INT NOT NULL,
	ThanhTien FLOAT DEFAULT 0,
	CONSTRAINT PK_LICHDATSAN PRIMARY KEY (MaLich),
	CONSTRAINT FK_LICHDATSAN_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	CONSTRAINT FK_LICHDATSAN_SANBONG FOREIGN KEY (MaSan) REFERENCES SANBONG(MaSan)
)

CREATE TABLE HOADON 
(
	MaHD INT IDENTITY(1,1) NOT NULL,
	NgayTao DATETIME DEFAULT GETDATE(),
	TongTien FLOAT DEFAULT 0,
	MaLich INT NOT NULL,
	MaKH INT NOT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY (MaHD),
	CONSTRAINT FK_HOADON_LICHDATSAN FOREIGN KEY (MaLich) REFERENCES LICHDATSAN(MaLich),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
)

CREATE TABLE DICHVU
(
	MaDV INT IDENTITY(1,1) NOT NULL,
	TenDV NVARCHAR(30) NOT NULL,
	DonGia INT DEFAULT 10000,
	CONSTRAINT PK_DICHVU PRIMARY KEY (MaDV)
)

CREATE TABLE CHITIETHD
(
	MaDV INT NOT NULL,
	MaHD INT NOT NULL,
	SoLuong INT DEFAULT 1,
	CONSTRAINT PK_CHITIETHD PRIMARY KEY (MaDV,MaHD),
	CONSTRAINT PK_CHITIETHD_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
	CONSTRAINT PK_CHITIETHD_DICHVU FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
)

-- cập nhật lại thành tiền của sân khi thay đổi giá thuê của loại sân
GO
CREATE TRIGGER UpdateTotalLoaiSan
ON LOAISAN
AFTER UPDATE
AS
BEGIN
	DECLARE @GIATHUE INT
	SET @GIATHUE = (SELECT GIATHUE FROM inserted)

    UPDATE LICHDATSAN
    SET THANHTIEN = @GIATHUE * DATEDIFF(hour, LICHDATSAN.THOIGIANBD, LICHDATSAN.THOIGIANKT)
    FROM LICHDATSAN, SANBONG
    WHERE (SELECT MALOAI FROM inserted) = SANBONG.MaLoai
	AND LICHDATSAN.MASAN = SANBONG.MASAN
END
GO

-- cập nhật thành tiền của sân khi đặt và Cập nhật tổng tiền hóa đơn khi thêm lịch đặt sân
GO
CREATE TRIGGER UpdateTotalLichDatSan
ON LICHDATSAN
AFTER INSERT,UPDATE
AS
BEGIN
	DECLARE @THOIGIANBD TIME,  @THOIGIANKT TIME
	SET @THOIGIANBD = (SELECT THOIGIANBD FROM inserted)
	SET @THOIGIANKT = (SELECT THOIGIANKT FROM inserted)

    UPDATE LICHDATSAN
    SET THANHTIEN = GIATHUE * DATEDIFF(hour, @THOIGIANBD, @THOIGIANKT)
    FROM SANBONG, LOAISAN
    WHERE (SELECT MASAN FROM inserted) = SANBONG.MASAN
	AND LOAISAN.MALOAI = SANBONG.MaLoai
	AND LICHDATSAN.MASAN = (SELECT MASAN FROM inserted)
END
GO

GO
CREATE TRIGGER UpdateTotalHoaDon
ON HOADON
AFTER INSERT
AS
BEGIN
	UPDATE HOADON
	SET TONGTIEN = THANHTIEN
	FROM HOADON, LICHDATSAN
	WHERE (SELECT MALICH FROM inserted) = LICHDATSAN.MALICH
	AND HOADON.MAHD = (SELECT MAHD FROM inserted)
END
GO

GO
CREATE TRIGGER UpdateTotalDichVu
ON DICHVU
AFTER UPDATE
AS
BEGIN
	DECLARE @DONGIA INT
	SET @DONGIA = (SELECT DONGIA FROM inserted)

    UPDATE HOADON
    SET TONGTIEN = THANHTIEN + @DONGIA * SOLUONG
    FROM LICHDATSAN, CHITIETHD, HOADON
    WHERE (SELECT MADV FROM inserted) = CHITIETHD.MADV
	AND HOADON.MAHD = CHITIETHD.MAHD
	AND HOADON.MALICH = LICHDATSAN.MALICH
END
GO

GO
CREATE TRIGGER UpdateTotalChiTietHD
ON CHITIETHD
AFTER INSERT,UPDATE
AS
BEGIN
	DECLARE @SOLUONG INT
	SET @SOLUONG = (SELECT SOLUONG FROM inserted)

    UPDATE HOADON
    SET TONGTIEN = THANHTIEN + DONGIA * @SOLUONG
    FROM LICHDATSAN, DICHVU, HOADON
    WHERE (SELECT MAHD FROM inserted) = HOADON.MAHD
	AND DICHVU.MADV = (SELECT MADV FROM inserted)
	AND HOADON.MALICH = LICHDATSAN.MALICH
END
GO

INSERT INTO ACCOUNT
VALUES ('admin1', '123456', N'Đạt', 1),
('nhanvien1', '1122', N'Tài', 0)

INSERT INTO LOAISAN
VALUES (N'Sân 5 Người', '100000'),
(N'Sân 7 Người', '300000'),
(N'Sân 11 Người', '1000000')

INSERT INTO SANBONG
VALUES (N'Sân 5 - 1', 1),
(N'Sân 7 - 1', 2),
(N'Sân 11 - 1', 3)

INSERT INTO KHACHHANG
VALUES (N'Nguyễn Văn An', N'TP.HCM', '0399127841'),
(N'Trần Văn Khánh', N'TP.HCM', '0399127841'),
(N'Bùi Văn Hùng', N'TP.HCM', '0399127841')

INSERT INTO LICHDATSAN (THOIGIANBD, THOIGIANKT, MAKH, MASAN)
VALUES ('11-20-2023 16:00', '11-20-2023 18:00', 1, 1)

INSERT INTO LICHDATSAN (THOIGIANBD, THOIGIANKT, MAKH, MASAN)
VALUES('11-20-2023 15:30', '11-20-2023 18:00', 2, 2)

INSERT INTO LICHDATSAN (THOIGIANBD, THOIGIANKT, MAKH, MASAN)
VALUES('11-20-2023 15:00', '11-20-2023 17:00', 3, 3)

INSERT INTO HOADON (MALICH, MAKH)
VALUES (1,1)

INSERT INTO HOADON (MALICH, MAKH)
VALUES(2,2)

INSERT INTO HOADON (MALICH, MAKH)
VALUES(3,3)

INSERT INTO DICHVU
VALUES (N'Nước uống Sting', 10000),
(N'Nước uống Olong', 10000),
(N'Mì xào', 30000)

INSERT INTO CHITIETHD
VALUES (1, 1, 5)

INSERT INTO CHITIETHD
VALUES(2, 2, 7)

INSERT INTO CHITIETHD
VALUES(3, 3, 11)

-- Stored Procedures Login
GO
CREATE PROC SP_Login
@username nvarchar(100), @password nvarchar(15)
AS 
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @username AND PASSWORD = @password
END
GO

-- Stored Procedures Quản lý sân
GO
CREATE PROC SP_GetListSan
AS
BEGIN
	SELECT * FROM SANBONG
END
GO

GO
CREATE PROC SP_KiemTraTrungTenSan
@TenSan nvarchar(100)
AS 
BEGIN
	SELECT * FROM SANBONG WHERE TenSan = @TenSan
END
GO

GO
CREATE PROC SP_ThemSan 
@TenSan nvarchar(100), @Maloai int
AS
BEGIN
	INSERT INTO SANBONG
	VALUES (@TenSan, @Maloai)
END
GO

GO
CREATE PROC SP_XoaSan 
@MaSan int
AS
BEGIN
	DELETE FROM SANBONG WHERE MASAN = @MaSan
END
GO

GO
CREATE PROC SP_SuaSan
@MaSan int, @TenSan nvarchar(100), @MaLoai int
AS
BEGIN
	UPDATE SANBONG
	SET TenSan = @TenSan, MaLoai = @MaLoai
	WHERE SANBONG.MaSan = @MaSan
END
GO

GO
CREATE PROC SP_TimKiemSan
@TenSan nvarchar(100)
AS
BEGIN
	SELECT * FROM SANBONG WHERE TENSAN LIKE '%' + @TenSan + '%'
END
GO

-- Stored Procedures Quản lý loại sân
GO
CREATE PROC SP_GetListLoaiSan
AS
BEGIN
	SELECT * FROM LOAISAN
END
GO

GO
CREATE PROC SP_KiemTraTrungTenLoai
@TenLoai nvarchar(100)
AS 
BEGIN
	SELECT * FROM LOAISAN WHERE TenLoai = @TenLoai
END
GO

GO
CREATE PROC SP_ThemLoaiSan
@TenLoai nvarchar(100), @GiaThue float
AS
BEGIN
	INSERT INTO LOAISAN
	VALUES (@TenLoai, @GiaThue)
END
GO

GO
CREATE PROC SP_XoaLoaiSan 
@MaLoai int
AS
BEGIN
	DELETE FROM LOAISAN WHERE Maloai = @MaLoai
END
GO

GO
CREATE PROC SP_SuaLoaiSan
@MaLoai int, @TenLoai nvarchar(100), @GiaThue float
AS
BEGIN
	UPDATE LOAISAN
	SET TenLoai = @TenLoai, GiaThue = @GiaThue
	WHERE LOAISAN.MaLoai = @MaLoai
END
GO

GO
CREATE PROC SP_TimKiemLoaiSan
@TenLoai nvarchar(100)
AS
BEGIN
	SELECT * FROM LOAISAN WHERE TenLoai LIKE '%' + @TenLoai + '%'
END
GO

-- Stored Procedures Quản lý lịch đặt sân
GO
CREATE PROC SP_GetListLichDatSan
AS
BEGIN
	SELECT * FROM LICHDATSAN
END
GO

GO
CREATE PROC SP_ThemLichDatSan
@ThoiGianBD DateTime, @ThoiGianKT DateTime, @MaKH int, @MaSan int
AS
BEGIN
	INSERT INTO LICHDATSAN (THOIGIANBD, THOIGIANKT, MAKH, MASAN)
	VALUES (@ThoiGianBD, @ThoiGianKT, @MaKH, @MaSan)
END
GO

GO
CREATE PROC SP_XoaLichDatSan
@MaLich int
AS
BEGIN
	DELETE FROM LICHDATSAN WHERE MaLich = @MaLich
END
GO

GO
CREATE PROC SP_SuaLichDatSan
@MaLich int, @ThoiGianBD DateTime, @ThoiGianKT DateTime, @MaKH int, @MaSan int
AS
BEGIN
	UPDATE LICHDATSAN
	SET ThoiGianBD = @ThoiGianBD, ThoiGianKT = @ThoiGianKT, MaKH = @MaKH, MaSan = @MaSan
	WHERE MaLich = @MaLich
END
GO